name: "CD"

on:
  workflow_dispatch:

jobs:
  call_schema_check:
    permissions: 
      contents: read
      packages: write
    uses: ./.github/workflows/schema_check.yml
    

  terraform:
   needs: call_schema_check
   permissions: 
      contents: read
      packages: write
      pull-requests: write 
      id-token: write
   uses: ./.github/workflows/terraform.yml
