name: Schema Check in CD
 
on: 
 workflow_call:
      
 
jobs:
  schema-check:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/environments
    #environment: apollo

    # https://docs.github.com/en/actions/reference/encrypted-secrets
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsenv
    #env:
      #APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      #APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.14.1 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      # only run this command with the `--background` flag if you have the Apollo Studio GitHub integration enabled on your repository
      - name: Run check against prod
        run: |
          rover graph check my-graph@prod --schema ./test.graphql --background

  schema-compose:
    if: github.event_name == 'push' && github.workflow == 'terraform.yml'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: supergraph compose
        run: |
              rover supergraph compose --config ./supergraphConfig.yaml | cat >> supergraph.graphql
  
  schema-publish:
   if: github.event_name == 'push' && github.workflow == 'terraform.yml'
   runs-on: ubuntu-latest

   steps:
      - uses: actions/checkout@v2

      - name: supergraph publish
        run: |
            rover subgraph publish my-supergraph@my-variant \
            --schema "./accounts/schema.graphql" \
            --name accounts \
            --routing-url "https://my-running-subgraph.com/api"
